baseURL = "http://jadetao.github.io/"
languageCode = "zh-CN"
title = "Jader"
theme = "nofancy"


[author]
    name = "Jader Tao"
    github = "JadeTao"
[params]
	# See themes/nofancy/static/highlight/styles for available options
	# i.e. "default", "github", "monokai".
	highlight="github-gist"
	
	# Controls what items are listed in the top nav menu
	# "none", or "categories"
	# If you have too many categories to fit in the top nav menu, set this to "none"
	topmenu="none"